#General Data
name: TheNewEconomy
version: 0.0.5.2
description: A feature-packed Bukkit Economy Plugin.
author: creatorfromhell

#Plugin Data
main: com.github.tnerevival.TNE
softdepend: [Vault, Essentials]


permissions:
   tne.*:
      description: Gives access to all TNE commands
      default: op
      children:
         tne.admin: true
         tne.admin.backup: true
         tne.admin.balance: true
         tne.admin.bank: true
         tne.admin.create: true
         tne.admin.delete: true
         tne.admin.history: true
         tne.admin.id: true
         tne.admin.help: true
         tne.admin.pin: true
         tne.admin.purge: true
         tne.admin.recreate: true
         tne.admin.reload: true
         tne.admin.save: true
         tne.admin.status: true
         tne.auction: true
         tne.auction.bid: true
         tne.auction.cancel: true
         tne.auction.claim: true
         tne.auction.end: true
         tne.auction.info: true
         tne.auction.list: true
         tne.auction.start: true
         tne.bank: true
         tne.bank.help: true
         tne.bank.add: true
         tne.bank.balance: true
         tne.bank.buy: true
         tne.bank.deposit: true
         tne.bank.price: true
         tne.bank.remove: true
         tne.bank.use: true
         tne.bank.withdraw: true
         tne.bypass: true
         tne.bypass.bank: true
         tne.bypass.inventory: true
         tne.bypass.nametag: true
         tne.bypass.vault: true
         tne.bypass.world: true
         tne.credit: true
         tne.credit.commands: true
         tne.credit.inventory: true
         tne.eco.clean: true
         tne.money: true
         tne.money.help: true
         tne.money.balance: true
         tne.money.give: true
         tne.money.history: true
         tne.money.set: true
         tne.money.take: true
         tne.money.pay: true
         tne.money.convert: true
         tne.package: true
         tne.package.list: true
         tne.package.buy: true
         tne.pin: true
         tne.pin.set: true
         tne.pin.confirm: true
         tne.shop: true
         tne.shop.admin: true
         tne.shop.add: true
         tne.shop.blacklist: true
         tne.shop.browse: true
         tne.shop.close: true
         tne.shop.create: true
         tne.shop.remove: true
         tne.shop.share: true
         tne.shop.stock: true
         tne.shop.toggle: true
         tne.shop.whitelist: true
         tne.place: true
         tne.place.bank: true
         tne.place.buy: true
         tne.place.sell: true
         tne.place.shop: true
         tne.use: true
         tne.use.bank: true
         tne.use.buy: true
         tne.use.sell: true
         tne.use.shop: true
         tne.vault: true
         tne.vault.help: true
         tne.vault.add: true
         tne.vault.buy: true
         tne.vault.remove: true
         tne.vault.use: true
         tne.vault.view: true

   tne.admin.*:
      description: Gives access to all TNE Admin Commands and bypasses.
      children:
         tne.admin: true
         tne.admin.backup: true
         tne.admin.balance: true
         tne.admin.bank: true
         tne.admin.create: true
         tne.admin.delete: true
         tne.admin.id: true
         tne.admin.help: true
         tne.admin.pin: true
         tne.admin.purge: true
         tne.admin.recreate: true
         tne.admin.reload: true
         tne.admin.save: true
         tne.admin.status: true
         tne.bypass.bank: true
         tne.bypass.inventory: true
         tne.bypass.nametag: true
         tne.bypass.world: true
         tne.shop.admin: true

   tne.auction.*:
      description: Gives access to all Auction Commands
      children:
         tne.auction.bid: true
         tne.auction.cancel: true
         tne.auction.claim: true
         tne.auction.end: true
         tne.auction.info: true
         tne.auction.list: true
         tne.auction.start: true

   tne.bank.*:
      description: Gives access to all TNE Bank Commands
      children:
         tne.bank: true
         tne.bank.help: true
         tne.bank.add: true
         tne.bank.balance: true
         tne.bank.buy: true
         tne.bank.deposit: true
         tne.bank.remove: true
         tne.bank.withdraw: true
         
   tne.bypass.*:
      description: Gives access to all TNE Bypasses
      children:
         tne.bypass: true
         tne.bypass.bank: true
         tne.bypass.inventory: true
         tne.bypass.nametag: true
         tne.bypass.vault: true
         tne.bypass.world: true
         
   tne.credit.*:
      description: Gives access to All TNE Credit Commands
      children:
         tne.credit: true
         tne.credit.commands: true
         tne.credit.inventory: true

   tne.eco.*:
      description: Gives access to all TNE Eco Commands
      children:
         tne.eco: true
         tne.eco.clean: true
   
   tne.lottery.*:
      description: Gives access to all TNE Lottery Commands
      children:
         tne.lottery.create: true
         tne.lottery.view: true

   tne.money.*:
      description: Gives access to all TNE Money Commands
      children:
         tne.money: true
         tne.money.help: true
         tne.money.balance: true
         tne.money.give: true
         tne.money.history: true
         tne.money.set: true
         tne.money.take: true
         tne.money.pay: true
         tne.money.convert: true
    
   tne.package.*:
      description: Gives access to all TNE Inventory Package Commands
      children:
         tne.package: true
         tne.package.list: true
         tne.package.buy: true
    
   tne.pin.*:
      description: Gives access to all TNE Pin Commands
      children:
         tne.pin: true
         tne.pin.set: true
         tne.pin.confirm: true

   tne.shop.*:
      description: Gives access to all shop-related features & commands.
      children:
         tne.shop: true
         tne.shop.add: true
         tne.shop.blacklist: true
         tne.shop.browse: true
         tne.shop.close: true
         tne.shop.create: true
         tne.shop.remove: true
         tne.shop.share: true
         tne.shop.stock: true
         tne.shop.toggle: true
         tne.shop.whitelist: true
         
   tne.place.*:
      description: Gives access to creating all sign types
      children:
         tne.place: true
         tne.place.bank: true
         tne.place.buy: true
         tne.place.sell: true
         tne.place.shop: true

   tne.use.*:
      description: Gives access to using all sign types.
      children:
         tne.use: true
         tne.use.bank: true
         tne.use.item: true
         tne.use.shop: true
         tne.use.vault: true

   tne.vault.*:
      description: Gives access to all TNE Bank Commands
      children:
         tne.vault: true
         tne.vault.help: true
         tne.vault.add: true
         tne.vault.buy: true
         tne.vault.remove: true
         tne.vault.use: true
         tne.vault.view: true